extends Spatial


# Declare member variables here. Examples:
# var a = 2
# var b = "text"


#These are terrible but will hopefully improve as problems become evident
#Units are 1000km, hours, and degrees
export var semimajor_axit = 10000
export var eccentricity = 0
export var angle_of_apoapsis = 42
export var xtilt = 0
export var ytilt = 0
export var daylen = 6
var orbital_period
var planet
var count

# Called when the node enters the scene tree for the first time.
func _ready():
	planet = get_child(0)
	self.rotate_y(angle_of_apoapsis)
	self.rotate_x(xtilt)
	self.rotate_z(ytilt)
	count = 0
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass
# warning-ignore:unused_argument
func _physics_process(delta):
	count += 1
	pass
